server:
  applicationConnectors:
    - type: http
      port: 18080
  adminConnectors:
    - type: http
      port: 18081

logging:
  loggers:
    jobscheduler: DEBUG

database:
  driverClass: org.h2.Driver
  user: sa
  password: 
  url: jdbc:h2:mem:tests;DB_CLOSE_DELAY=1
